@Bite.Api_HostAddress = http://localhost:5126
@RestaurantApiKey = replace-with-api-key

GET {{Bite.Api_HostAddress}}/api/restaurants/2/menu
Accept: application/json

### Register a new Restaurant try this values in swagger ui (https://localhost:7046/swagger)
POST {{Bite.Api_HostAddress}}/api/restaurants
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="Name"

Restaurant Station 183
--WebAppBoundary
Content-Disposition: form-data; name="Street"

Softwarepark
--WebAppBoundary
Content-Disposition: form-data; name="Number"

15
--WebAppBoundary
Content-Disposition: form-data; name="ZipCode"

4232
--WebAppBoundary
Content-Disposition: form-data; name="City"

Hagenberg
--WebAppBoundary
Content-Disposition: form-data; name="Country"

Austria
--WebAppBoundary
Content-Disposition: form-data; name="Longitude"

14.514449032326327
--WebAppBoundary
Content-Disposition: form-data; name="Latitude"

48.368368883920425
--WebAppBoundary
Content-Disposition: form-data; name="WebhookUrl"

https://api.nimmersatt.at/bite
--WebAppBoundary
Content-Disposition: form-data; name="OpeningHoursJson"
Content-Type: application/json

[
  { "DayOfWeek": 1, "OpenTime": "11:00:00", "CloseTime": "15:00:00" },
  { "DayOfWeek": 1, "OpenTime": "17:00:00", "CloseTime": "22:00:00" },
  { "DayOfWeek": 2, "OpenTime": "11:00:00", "CloseTime": "14:00:00" }
]
--WebAppBoundary
Content-Disposition: form-data; name="CoverImage"; filename="restaurant.jpg"
Content-Type: image/png

< ./beispiel.png
--WebAppBoundary--

### Get Restaurants
GET {{Bite.Api_HostAddress}}/api/restaurants?latitude=48.368368883920425&longitude=14.514449032326327&openNow=true&count=10
Accept: application/json

### Replace restaurant menu
PUT {{Bite.Api_HostAddress}}/restaurants/2/menu
Content-Type: application/json
X-Api-Key: {{RestaurantApiKey}}

{
  "categories": [
    {
      "name": "Pizza",
      "items": [
        {
          "name": "Margherita",
          "description": "Tomaten, Kaese",
          "price": 9.59
        },
        {
          "name": "Al Tonno",
          "description": "Tomaten, Kaese, Thunfisch, Zwiebel, Oliven",
          "price": 11
        },
        {
          "name": "Spinaci",
          "description": "Tomaten, Kaese, Spinat, Feta",
          "price": 10
        }
      ]
    },
    {
      "name": "Pasta",
      "items": [
        {
          "name": "Lasagne al Forno",
          "description": "mit Rinderfaschiertem",
          "price": 12
        },
        {
          "name": "Spaghetti Frutti di Mare",
          "description": "mit Meeresfruechten in Weissweinsauce",
          "price": 14
        }
      ]
    }
    }
    }

### Place order
    POST {{Bite.Api_HostAddress}}/api/restaurants/2/orders
    Content-Type: application/json

    {
    "items": [
    {
      "menuItemId": 1,
      "quantity": 1
    },
    {
      "menuItemId": 2,
      "quantity": 2
    }
    ],
    "deliveryAddress": {
    "street": "Softwarepark",
    "number": "23",
    "zipCode": "4232",
    "city": "Hagenberg",
    "country": "Austria",
    "latitude": 48.3692673,
    "longitude": 14.5125979,
    "additionalInfo": "Zimmer 404"
    }
    }
###
PUT {{Bite.Api_HostAddress}}/api/restaurants/2/delivery-conditions
X-Api-Key: {{RestaurantApiKey}}
Content-Type: application/json

[
  {
    "maxDistance": 10.0,
    "minOrderValue": 20.0,
    "feeRules": [
      {
        "maxOrderValue": 0.0,
        "deliveryFee": 0.0
      }
    ]
  },
  {
    "maxDistance": 1000.0,
    "minOrderValue": 20.0,
    "feeRules": [
      {
        "maxOrderValue": 30.0,
        "deliveryFee": 5.0
      },
      {
        "maxOrderValue": 0.0,
        "deliveryFee": 0.0
      }
    ]
  }
]

### Calculate order price
POST {{Bite.Api_HostAddress}}/api/restaurants/1/orders/price
Content-Type: application/json

{
  "items": [
    {
      "menuItemId": 1,
      "quantity": 1
    },
    {
      "menuItemId": 2,
      "quantity": 2
    }
  ],
  "deliveryAddress": {
    "street": "Softwarepark",
    "number": "23",
    "zipCode": "4232",
    "city": "Hagenberg",
    "country": "Austria",
    "latitude": 48.3692673,
    "longitude": 14.5125979,
    "additionalInfo": "Zimmer 404"
  }
}


### Get Status of an Order

GET {{Bite.Api_HostAddress}}/api/orders/A6C3DD91/status