<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bite.Api\Bite.Api.csproj" />
    <ProjectReference Include="..\Bite.Dal\Bite.Dal.csproj" />
  </ItemGroup>

</Project>
